/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package almacen.cacao;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;
//import javax.swing.JTable;
//import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andres
 */
public class CalculadoraDeCacao extends javax.swing.JFrame {
public String Cliente;
public String tipoCacao;
public  double cantidadCacao;
public  double cantidadCacaoBruto;
public  double precioCacao;
public  double precioBruto;
public  double porCentajePrecio= 50;
public  double porcentajeQuintal= 0.38;
public  double resultadoCacao;
//private DefaultTableModel tabla;
    /**
     * Creates new form CalculadoraDeCacao
     */
    public CalculadoraDeCacao() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        lblNombreCliente = new java.awt.Label();
        lblTipoCacao = new java.awt.Label();
        lblCantidadCacao = new java.awt.Label();
        lblPrecioCacao = new java.awt.Label();
        lblTotalAPagar = new java.awt.Label();
        txtNombreCliente = new javax.swing.JTextField();
        txtTipoCacao = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        txtCantidadCacao = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        txtPrecioCacao = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        lblFecha = new java.awt.Label();
        txtFecha = new javax.swing.JTextField();
        lblVendedor = new java.awt.Label();
        txtVendedor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Engravers MT", 0, 48)); // NOI18N
        label1.setText("Calculadora Cacao");

        lblNombreCliente.setText("Nombre del Cliente");

        lblTipoCacao.setText("Tipo ");

        lblCantidadCacao.setText("Cantidad");

        lblPrecioCacao.setText("Precio");

        lblTotalAPagar.setText("Total a Pagar");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        lblFecha.setText("Fecha");

        lblVendedor.setText("Vendedor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(lblTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(btnCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar)
                        .addGap(29, 29, 29)
                        .addComponent(btnImprimir)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipoCacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCantidadCacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPrecioCacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTipoCacao, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(txtCantidadCacao)
                                    .addComponent(txtPrecioCacao)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(txtVendedor))))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(129, 129, 129)))
                        .addGap(1, 1, 1)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoCacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoCacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCantidadCacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadCacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecioCacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioCacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(lblTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir)
                    .addComponent(btnCalcular)
                    .addComponent(btnGuardar)
                    .addComponent(btnBorrar)
                    .addComponent(btnConsultar))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
//        if (txtNombreCliente.getText().isEmpty() || txtTipoCacao.getText().isEmpty()|| txtCantidadCacao.getText().isEmpty()|| txtPrecioCacao.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Los Campos estan vacios. Por favor Llena los campos.");
//        } else if (txtNombreCliente.isEnum) {
//            
//        }else {
//            cantidadCacao = Double.parseDouble(txtCantidadCacao.getText());
//            cantidadCacaoBruto = Double.parseDouble(txtCantidadCacao.getText());
//            precioBruto = Double.parseDouble(txtPrecioCacao.getText());
//            cantidadCacao= Math.floor(cantidadCacaoBruto * porcentajeQuintal);
//            precioCacao = precioBruto / porCentajePrecio;
//            resultadoCacao= cantidadCacao* precioCacao;
////            System.out.print(cantidadCacao);
//            lblTotalAPagar.setForeground(Color.red);
//            lblTotalAPagar.setText("El Total a pagar es: " + resultadoCacao);
//        } 
//        if (txtNombreCliente.getText().isEmpty() || txtTipoCacao.getText().isEmpty() || txtCantidadCacao.getText().isEmpty() || txtPrecioCacao.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Los Campos están vacíos. Por favor llena los campos.");
//        } else {
//            try {
//                cantidadCacaoBruto = Double.parseDouble(txtCantidadCacao.getText());
//                precioBruto = Double.parseDouble(txtPrecioCacao.getText());
//                if (Double.isNaN(cantidadCacaoBruto) || Double.isNaN(precioBruto)) {
//                    JOptionPane.showMessageDialog(null, "Por favor ingresa valores numéricos válidos en los campos de cantidad y precio de cacao.");
//                } else if (!Cliente.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+") || !tipoCacao.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+")) {
//                    JOptionPane.showMessageDialog(null, "Por favor ingresa solo texto en los campos de nombre de cliente y tipo de cacao.");
//                } else {
//                    cantidadCacao = Math.floor(cantidadCacaoBruto * porcentajeQuintal);
//                    precioCacao = precioBruto / porCentajePrecio;
//                    resultadoCacao = cantidadCacao * precioCacao;
//                    lblTotalAPagar.setForeground(Color.RED);
//                    lblTotalAPagar.setText("El Total a pagar es: " + resultadoCacao);
//                }
//            } catch (NumberFormatException e) {
//                JOptionPane.showMessageDialog(null, "Por favor ingresa valores numéricos válidos en los campos de cantidad y precio de cacao.");
//            }
//        }

        long resultadoRedondiado;
        if (!txtFecha.getText().isEmpty() && txtVendedor.getText().isEmpty() && txtNombreCliente.getText().isEmpty() && !txtTipoCacao.getText().isEmpty() && !txtCantidadCacao.getText().isEmpty() && !txtPrecioCacao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Los Campos están vacíos. Por favor llena los campos.");
        } else {
            try {
                cantidadCacaoBruto = Double.parseDouble(txtCantidadCacao.getText());
                precioBruto = Double.parseDouble(txtPrecioCacao.getText());

                // Verificar si los valores son números válidos
                if (Double.isNaN(cantidadCacaoBruto) || Double.isNaN(precioBruto)) {
                    JOptionPane.showMessageDialog(null, "Por favor ingresa valores numéricos válidos en los campos de cantidad y precio de cacao.");
                } else {
                    try {
                        Cliente = txtNombreCliente.getText();
                        tipoCacao = txtTipoCacao.getText();

                        // Verificar si los valores son texto válido
                        if (!Cliente.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+") || !tipoCacao.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+")) {
                            throw new IllegalArgumentException("Por favor ingresa solo texto en los campos de nombre de cliente y tipo de cacao.");
                        } else {
                            cantidadCacao = Math.floor(cantidadCacaoBruto * porcentajeQuintal);
                            precioCacao = precioBruto / porCentajePrecio;
                            resultadoCacao = cantidadCacao * precioCacao;
                            resultadoRedondiado = Math.round(resultadoCacao);
                            lblTotalAPagar.setForeground(Color.RED);
                            lblTotalAPagar.setText("El Total a pagar es: " + resultadoRedondiado);
                        }
                    } catch (IllegalArgumentException e) {
                        JOptionPane.showMessageDialog(null, e.getMessage());
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Por favor ingresa valores numéricos válidos en los campos de cantidad y precio de cacao.");
            }
        }


    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        boolean camposVaciados = false;
        if (!txtFecha.getText().isEmpty() && txtVendedor.getText().isEmpty() && txtNombreCliente.getText().isEmpty() && !txtTipoCacao.getText().isEmpty() && !txtCantidadCacao.getText().isEmpty() && !txtPrecioCacao.getText().isEmpty()) {
            txtFecha.setText(" ");
            txtVendedor.setText(" ");
            txtNombreCliente.setText(" ");
            txtTipoCacao.setText(" ");
            txtCantidadCacao.setText(" ");
            txtPrecioCacao.setText(" ");
            lblTotalAPagar.setText(" ");
            camposVaciados = true;
            JOptionPane.showMessageDialog(null, "Se borraron los Campos Exitosamente.");
        } else if (txtFecha.getText().isEmpty() && txtVendedor.getText().isEmpty() && txtNombreCliente.getText().isEmpty() && txtTipoCacao.getText().isEmpty() && txtCantidadCacao.getText().isEmpty() && txtPrecioCacao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se Pudieron borrar los Campos porque estan vacio. Cuando esten llenos Podrar dar Clic al Boton Borrar");
        } else {
            JOptionPane.showMessageDialog(null, "No se Pudieron borrar los Campos porque ya lo hizo. Debe llenar los campos antes de borrarlos.");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
//        Cliente= String.valueOf(txtNombreCliente.getText());
//        tipoCacao= String.valueOf(txtNombreCliente.getText());
//        cantidadCacao= Double.valueOf(txtCantidadCacao.getText());
//        tabla.addRow(new Object[]{ Cliente, tipoCacao, cantidadCacao});
//        try {
//            Cliente = txtNombreCliente.getText();
//            tipoCacao = txtTipoCacao.getText(); // Assumes you have a text field named txtTipoCacao
//            cantidadCacao = Double.parseDouble(txtCantidadCacao.getText());
//
//            tabla.addRow(new Object[]{Cliente, tipoCacao, cantidadCacao});
//        } catch (NumberFormatException e) {
//            javax.swing.JOptionPane.showMessageDialog(this, "La cantidad de cacao debe ser un número.", "Error de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
//        } catch (Exception e) {
//            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al guardar los datos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
//        }
//        try {
//            FileWriter archivofacrura = new FileWriter("src/Base de Datos txt/Almacen Cliente.txt");
//            BufferedWriter escribe = new BufferedWriter(archivofacrura);
//            escribe.write(txtFecha.getText());
//            escribe.write(txtVendedor.getText());
//            escribe.write(txtNombreCliente.getText());
//            escribe.write(txtTipoCacao.getText());
//            escribe.write(txtCantidadCacao.getText());
//            escribe.write(txtPrecioCacao.getText());
//            escribe.write(lblTotalAPagar.getText());
//            escribe.close();
//        } catch (Exception ex) {
//             ex.printStackTrace();
//        }

try {
    FileWriter archivofacrura = new FileWriter("src/Base de Datos txt/Almacen Cliente.txt",true);
    BufferedWriter escribe = new BufferedWriter(archivofacrura);

    // Obtenemos los textos de cada campo y los combinamos en una sola línea con comas
    String linea = String.join(",",
        txtFecha.getText(),
        txtVendedor.getText(),
        txtNombreCliente.getText(),
        txtTipoCacao.getText(),
        txtCantidadCacao.getText(),
        txtPrecioCacao.getText(),
        lblTotalAPagar.getText()
    );

    // Escribimos la línea en el archivo
    escribe.write(linea);
    escribe.newLine(); // Añade una nueva línea después de cada registro

    escribe.close();
} catch (Exception ex) {
    ex.printStackTrace();
}


    

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
         Inventario ver = new Inventario();
         ver.setVisible(true);
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDeCacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDeCacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDeCacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDeCacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                Inventario inventario = new Inventario();
//                new CalculadoraDeCacao(inventario.getTabla()).setVisible(true);
                new CalculadoraDeCacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.Label label1;
    private java.awt.Label lblCantidadCacao;
    private java.awt.Label lblFecha;
    private java.awt.Label lblNombreCliente;
    private java.awt.Label lblPrecioCacao;
    private java.awt.Label lblTipoCacao;
    private java.awt.Label lblTotalAPagar;
    private java.awt.Label lblVendedor;
    private javax.swing.JTextField txtCantidadCacao;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtPrecioCacao;
    private javax.swing.JTextField txtTipoCacao;
    private javax.swing.JTextField txtVendedor;
    // End of variables declaration//GEN-END:variables
}
