/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package almacen.cacao;

import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres
 */
public class IncioSencion extends javax.swing.JFrame {
 public String archivoRemoto = "src/Base de Datos txt/Registro Usuario.txt";
    /**
     * Creates new form IncioSencion
     */
    public IncioSencion() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jpContrasena = new javax.swing.JPasswordField();
        rbtnMostrarContrasena = new javax.swing.JRadioButton();
        btnRegistroSeccion = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Engravers MT", 0, 45)); // NOI18N
        jLabel1.setText("Inicia Sesion");

        jLabel2.setText("Nombre de Usuario");

        jLabel3.setText("Contraseña");

        jpContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpContrasenaActionPerformed(evt);
            }
        });

        rbtnMostrarContrasena.setText("Mostrar Contraseña");
        rbtnMostrarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMostrarContrasenaActionPerformed(evt);
            }
        });

        btnRegistroSeccion.setText("Registrarse");

        btnInicio.setText("Iniciar Sesion");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jpContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnInicio)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistroSeccion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnMostrarContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jpContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnMostrarContrasena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInicio)
                    .addComponent(btnRegistroSeccion))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
CamposValidadores();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void jpContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpContrasenaActionPerformed

    private void rbtnMostrarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMostrarContrasenaActionPerformed
       if (rbtnMostrarContrasena.isSelected()) {
                    jpContrasena.setEchoChar((char) 0); // Muestra la contraseña
                } else {
                    jpContrasena.setEchoChar('*'); // Oculta la contraseña
                }
    }//GEN-LAST:event_rbtnMostrarContrasenaActionPerformed

    private void validacionInicioUsuario(){
//        String lineaLectora = null;
//        boolean existe = false;
//        boolean entrar = true;
//        String Usuario = btnInicio.getText();
//        char[] contrasenaArreglo = jpContrasena.getPassword();
//        String contrasena = new String(contrasenaArreglo);
//
//        try {
//            FileReader entradalectora = new FileReader(archivoRemoto);
//            BufferedReader Lector = new BufferedReader(Lector);
//
//            while ((lineaLectora = Lector.readLine()) != null) {
//                String[] palabrasSeparada = lineaLectora.split(" "); // dividir en palabras delimitadas por espacios
//                if (palabrasSeparada[0].equals(Usuario) && palabrasSeparada[1].equals(contrasenaArreglo)) {
//                    JOptionPane.showMessageDialog(null, "Gracias por Iniciar. Seccion puede continuar.");
//                    MenuDeOPciones menu = new MenuDeOPciones();
//                    menu.setVisible(entrar);
//                    existe = true;
//                }
//            }
//
//            if (!existe) {
//                System.out.println("Usuario o contraseña incorrecto. Por favor intentelo de nuevo");
//            }
//        } catch (Exception e) {
//            e.getCause();
//        }
   String lineaLectora = null;
        boolean existe = false;
        boolean entrar = true;
        String Usuario = txtUsuario.getText();
        char[] contrasenaArreglo = jpContrasena.getPassword();
        String contrasena = new String(contrasenaArreglo);

        try {
            FileReader entradalectora = new FileReader(archivoRemoto);
            BufferedReader lector = new BufferedReader(entradalectora);

            while ((lineaLectora = lector.readLine()) != null) {
                String[] palabrasSeparada = lineaLectora.split(","); // dividir en palabras delimitadas por espacios
                if (palabrasSeparada[0].equals(Usuario) && palabrasSeparada[1].equals(contrasena)) {
                    JOptionPane.showMessageDialog(null, "Gracias por iniciar sesión. Puede continuar.");
                    MenuDeOPciones menu = new MenuDeOPciones();
                    menu.setVisible(entrar);
                    existe = true;
                    break;
                }
            }

            if (!existe) {
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos. Por favor inténtelo de nuevo.");
            }

            lector.close(); // Cerrar el lector después de usarlo
        } catch (Exception e) {
            e.printStackTrace(); // Imprimir la traza del error
        }
    }
            private void CamposValidadores(){
                String Usuario = txtUsuario.getText();
        char[] contrasenaArreglo = jpContrasena.getPassword();
        String contrasena = new String(contrasenaArreglo);
    if (!Usuario.isEmpty() && !contrasena.isEmpty()) {
        validacionInicioUsuario();
    } else {
        JOptionPane.showMessageDialog(null, "El registro no se ha podido completar. por favor llene los campos");
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introducedentradalectora Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncioSencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncioSencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncioSencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncioSencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IncioSencion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegistroSeccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jpContrasena;
    private javax.swing.JRadioButton rbtnMostrarContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
