/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package almacen.cacao;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres
 */
public class IncioSencion extends javax.swing.JFrame {

 public String archivoRemoto = System.getProperty("user.home") + File.separator + "Registro Usuario.txt";
    /**
     * Creates new form IncioSencion
     */
    public IncioSencion() {
        initComponents();
        this.setTitle("Iniciar Seccion");
        this.setSize(615, 310);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jpContrasena = new javax.swing.JPasswordField();
        rbtnMostrarContrasena = new javax.swing.JRadioButton();
        btnInicio = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Engravers MT", 0, 45)); // NOI18N
        jLabel1.setText("Inicia Sesion");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 20, 477, 54);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel2.setText(" Usuario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 103, 140, 23);

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 147, 140, 30);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(150, 100, 182, 22);

        jpContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(jpContrasena);
        jpContrasena.setBounds(150, 150, 239, 22);

        rbtnMostrarContrasena.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        rbtnMostrarContrasena.setText("Mostrar Contraseña");
        rbtnMostrarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMostrarContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnMostrarContrasena);
        rbtnMostrarContrasena.setBounds(350, 108, 270, 30);

        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/BotonInicio.png"))); // NOI18N
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio);
        btnInicio.setBounds(150, 210, 200, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Portadas/Proyecto fondos de pantalla aplicacion cacao.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 600, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed

        CamposValidadores();

    }//GEN-LAST:event_btnInicioActionPerformed

    private void jpContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpContrasenaActionPerformed

    private void rbtnMostrarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMostrarContrasenaActionPerformed
        if (rbtnMostrarContrasena.isSelected()) {
            jpContrasena.setEchoChar((char) 0); // Muestra la contraseña
        } else {
            jpContrasena.setEchoChar('*'); // Oculta la contraseña
        }
    }//GEN-LAST:event_rbtnMostrarContrasenaActionPerformed

    private void validacionInicioUsuario() {
        String lineaLectora = null;
        boolean existe = false;
        boolean entrar = true;
        String Usuario = txtUsuario.getText();
        char[] contrasenaArreglo = jpContrasena.getPassword();
        String contrasena = new String(contrasenaArreglo);
        
        try {
            // Leer el archivo desde la ubicación especificada en el sistema de archivos del usuario
            File archivo = new File(archivoRemoto);
            if (archivo.exists()) {
                BufferedReader lector = new BufferedReader(new FileReader(archivo));

                while ((lineaLectora = lector.readLine()) != null) {
                    String[] palabrasSeparada = lineaLectora.split(",");
                    if (palabrasSeparada[0].equals(Usuario) && palabrasSeparada[1].equals(contrasena)) {
                        JOptionPane.showMessageDialog(null, "Gracias por iniciar sesión. Puede continuar.");
                        MenuDeOPciones menu = new MenuDeOPciones(Usuario);
                        menu.setVisible(entrar);
                        this.dispose();
                        existe = true;
                        break;
                    }
                }

                if (!existe) {
                    JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos. Por favor inténtelo de nuevo.");
                }

                lector.close();
            } else {
                JOptionPane.showMessageDialog(null, "Error al cargar el archivo de registro de usuarios. El archivo no fue encontrado.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
//        String lineaLectora = null;
//        boolean existe = false;
//        boolean entrar = true;
//        String Usuario = txtUsuario.getText();
//        char[] contrasenaArreglo = jpContrasena.getPassword();
//        String contrasena = new String(contrasenaArreglo);
//        try {
//            InputStream entradaLectora = getClass().getResourceAsStream(archivoRemoto);
//
//            if (entradaLectora != null) { 
//                BufferedReader lector = new BufferedReader(new InputStreamReader(entradaLectora));
//
//                while ((lineaLectora = lector.readLine()) != null) {
//                    String[] palabrasSeparada = lineaLectora.split(",");
//                    if (palabrasSeparada[0].equals(Usuario) && palabrasSeparada[1].equals(contrasena)) {
//                        JOptionPane.showMessageDialog(null, "Gracias por iniciar sesión. Puede continuar.");
//                        MenuDeOPciones menu = new MenuDeOPciones(Usuario);
//                        menu.setVisible(entrar);
//                        this.dispose();
//                        existe = true;
//                        break;
//                    }
//                }
//
//                if (!existe) {
//                    JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos. Por favor inténtelo de nuevo.");
//                }
//
//                lector.close();
//            } else {
//                JOptionPane.showMessageDialog(null, "Error al cargar el archivo de registro de usuarios. El archivo no fue encontrado.");
//            }
//        } catch (Exception e) {
//             e.printStackTrace();
//        }
    }

    private void CamposValidadores() {
        String Usuario = txtUsuario.getText();
        char[] contrasenaArreglo = jpContrasena.getPassword();
        String contrasena = new String(contrasenaArreglo);
        if (!Usuario.isEmpty() && !contrasena.isEmpty()) {
            validacionInicioUsuario();
        } else {
            JOptionPane.showMessageDialog(null, "El registro no se ha podido completar. por favor llene los campos");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introducedentradalectora Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncioSencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncioSencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncioSencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncioSencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IncioSencion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jpContrasena;
    private javax.swing.JRadioButton rbtnMostrarContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
