/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package almacen.cacao;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Inventario extends javax.swing.JFrame {

    public String ArchivoFactura = System.getProperty("user.home") + File.separator + "Almacen Cliente.txt";
    DefaultTableModel tabla = new DefaultTableModel();

    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
        this.setTitle("Inventario Cacao");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        agregarElemento();
        CargarInventario();
        actualizarTotales();
    }

    public void agregarElemento() {
        String Elementos[] = {"Fecha", "Vendedor", "Cliente", "Tipo Cacao", "Cantidad de Cacao", "Precio a Pagar", "Pago de Cacao"};
        tabla.setColumnIdentifiers(Elementos);
        tablaInventario.setModel(tabla);
    }

    public DefaultTableModel getTabla() {
        return tabla;
    }

    public void CargarInventario() {
//         try {
//             FileReader lector = new FileReader(ArchivoFactura);
//             BufferedReader leer = new BufferedReader(lector);
//             String linea;
//             boolean primeraLinea = true;
//             while ((linea = leer.readLine()) != null) {
//                  String[] datos = linea.split(",");
//                  if (primeraLinea) {
//                     tabla.setColumnIdentifiers(datos);
//                     primeraLinea = false;
//                 } else {
//                      tabla.addRow(datos);
//                 }
//             }    
//                
//         } catch (Exception e) {
//             e.printStackTrace();
//         }
        try {
            FileReader lector = new FileReader(ArchivoFactura);
            BufferedReader leer = new BufferedReader(lector);
            String linea;
            // Leer las líneas restantes
            while ((linea = leer.readLine()) != null) {
                String[] datos = linea.split(",");
                // Agregar datos a la tabla
                tabla.addRow(datos);
            }

            leer.close();
            lector.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void actualizarTotales() {
        int totalCacao = 0;
        double totalGastado = 0.0;

        for (int i = 0; i < tabla.getRowCount(); i++) {
            // Obtener los valores de la columna "Cantidad de Cacao" (índice 4) y "Pago de Cacao" (índice 5)
            String cantidadStr = (String) tabla.getValueAt(i, 4);
            String pagoStr = (String) tabla.getValueAt(i, 6);

            try {
                // Sumar la cantidad de cacao
                int cantidad = Integer.parseInt(cantidadStr);
                totalCacao += cantidad;
            } catch (NumberFormatException e) {
                // Manejar el caso cuando la cantidad no es un número válido
                System.err.println("Formato de cantidad no válido: " + cantidadStr);
            }

            try {
                // Sumar el pago de cacao
                double pago = Double.parseDouble(pagoStr);
                totalGastado += pago;
            } catch (NumberFormatException e) {
                // Manejar el caso cuando el pago no es un número válido
                System.err.println("Formato de pago no válido: " + pagoStr);
            }
        }

        // Actualizar las etiquetas
        lblTotalCacao.setText("Cantidad Total de Cacao = " + totalCacao);
        lblTotalGastado.setText("Cantidad Total Gastado = " + totalGastado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTotalCacao = new javax.swing.JLabel();
        lblTotalGastado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Engravers MT", 0, 48)); // NOI18N
        jLabel1.setText("Inventario Cacao");

        lblTotalCacao.setText("Cantidad Total de Cacao=");

        lblTotalGastado.setText("Cantidad Total Gastado=");

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaInventario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTotalCacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(lblTotalGastado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalCacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalGastado)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTotalCacao;
    private javax.swing.JLabel lblTotalGastado;
    private javax.swing.JTable tablaInventario;
    // End of variables declaration//GEN-END:variables
}
