/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package almacen.cacao;

/**
 *
 * @author Usuario
 */
public class MenuDeOPciones extends javax.swing.JFrame {

    /**
     * Creates new form MenuDeOPciones
     */
    public MenuDeOPciones(String usuario) {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Menu de Opciones- Usuario Actual: " + usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblMenuCalculadora = new javax.swing.JLabel();
        lblMenuInventario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        jLabel2.setText("Bienvenido a su Menu Cacao");
        panelMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1074, 61));

        lblMenuCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Calculadora Cacao Icono.png"))); // NOI18N
        lblMenuCalculadora.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblMenuCalculadora.setAlignmentY(-50.0F);
        lblMenuCalculadora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMenuCalculadora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblMenuCalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuCalculadoraMouseClicked(evt);
            }
        });
        panelMenu.add(lblMenuCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 127, 308, -1));

        lblMenuInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Inventario Cacao.png"))); // NOI18N
        lblMenuInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMenuInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuInventarioMouseClicked(evt);
            }
        });
        panelMenu.add(lblMenuInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 127, 318, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Portadas/portadacacao.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        panelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 1040, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMenuCalculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuCalculadoraMouseClicked
        CalculadoraDeCacao menuCalculadora = new CalculadoraDeCacao();
        menuCalculadora.setVisible(true);
    }//GEN-LAST:event_lblMenuCalculadoraMouseClicked

    private void lblMenuInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuInventarioMouseClicked
        Inventario menuInventario = new Inventario();
        menuInventario.setVisible(true);
    }//GEN-LAST:event_lblMenuInventarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDeOPciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDeOPciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDeOPciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDeOPciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDeOPciones("Sin iniciar Sesion").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblMenuCalculadora;
    private javax.swing.JLabel lblMenuInventario;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
