/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package almacen.cacao;

import java.awt.AlphaComposite;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Andres
 */
public class MenuInicio extends javax.swing.JFrame {
    /**
     * Creates new form MenuInicio
     */
//    FondoInicio fondo = new FondoInicio();
    public MenuInicio() {
        initComponents();
        this.setTitle("Menu Inicio");
        this.setExtendedState(MenuInicio.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
//        this.setContentPane(fondo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel.setFont(new java.awt.Font("Engravers MT", 0, 48)); // NOI18N
        JPanel.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        jLabel2.setText("Bienvenido a Almacen Cacao");
        JPanel.add(jLabel2);
        jLabel2.setBounds(160, 30, 1045, 58);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ProyectofondosBoton.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        JPanel.add(jLabel3);
        jLabel3.setBounds(435, 137, 607, 208);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Portadas/portadacacao.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        JPanel.add(jLabel4);
        jLabel4.setBounds(0, 0, 1460, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1208, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        iniciarMenuSeccionRegistro();
    }//GEN-LAST:event_jLabel3MouseClicked
private void iniciarMenuSeccionRegistro(){
    String[] opciones = {"Iniciar Sesión", "Registrar Usuario"};
        int opcion = JOptionPane.showOptionDialog(
            null,
            "¿Qué desea hacer?",
            "Seleccione una opción",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null,
            opciones,
            opciones[0]
        );

        if (opcion == 0) {
            iniciarMenuSeccion();
        } else if (opcion == 1) {
            iniciarMenuRegistro();
        }
}

private void iniciarMenuSeccion(){
//  IncioSencion iniciar = new IncioSencion();
//  iniciar.setVisible(true);
  try {
        IncioSencion iniciar = new IncioSencion();
        iniciar.setVisible(true);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al abrir la ventana de Iniciar Sesión: " + e.getMessage());
    }
}
private void iniciarMenuRegistro(){
//     RegistroUsuario iniciar = new RegistroUsuario();
//  iniciar.setVisible(true);
try {
        RegistroUsuario iniciar = new RegistroUsuario();
        iniciar.setVisible(true);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al abrir la ventana de Registro de Usuario: " + e.getMessage());
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
//class FondoInicio extends JPanel {
//        Image imagen;
////        @Override
////        public void paint(Graphics g) {
////            try {
////                imagen = new ImageIcon(getClass().getResource("/Portadas/portadacacao.png")).getImage();
////                g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
////                setOpaque(false);
////            } catch (Exception e) {
////                System.out.println("No se pudo cargar la imagen: " + e.getMessage());
////            }
////            super.paint(g);
////        }
//
//        @Override
//        protected void paintComponent(Graphics g) {
//            super.paintComponent(g);
//            imagen = new ImageIcon(getClass().getResource("/Portadas/portadacacao.png")).getImage();
//            g.drawImage(imagen, 0, 0, this.getWidth(), this.getHeight(), MenuInicio.this);
//              setOpaque(false);
//        }
//
//    }  
}